
services:
    pico:
        hostname: pico-build
        build: .
        volumes:
        - ../:/home/pico-build
        command:
            sh -c ' 
            cd /home/pico-build/pico && 
            mkdir -p build && 
            cd build && 
            CC=arm-none-eabi-gcc CXX=arm-none-eabi-g++ cmake -DCMAKE_BUILD_TYPE=Debug .. && 
            make
            '
