[package]
name = "webserver"
version = "0.2.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
base64 = "0.22.1"
chrono = "0.4.38"
tokio = { version = "1.41.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }
