address = "127.0.0.1"
port_http = 8080
port_https = 8443
disable_http = false
disable_https = true
#enable_http_api = true     # Override that takes effect when disable_http is true
db_dir = "./db"
assets_dir = "./assets"
certs_dir = "./certs"
