#ifndef BUFFER_SIZE
#define BUFFER_SIZE 512
#endif

#ifndef RETRIES
#define RETRIES 3
#endif

#ifndef RESPONSE_WAIT_TIME
#define RESPONSE_WAIT_TIME 5000
#endif

#ifndef NUM_OF_RETRIES_FOR_PICO_MESSAGE
#define NUM_OF_RETRIES_FOR_PICO_MESSAGE 3
#endif

#ifndef PICO_RESPONSE_WAIT_TIME
#define PICO_RESPONSE_WAIT_TIME 3000
#endif

#ifndef GET_REQUEST_TIMER_PERIOD
#define GET_REQUEST_TIMER_PERIOD 5000
#endif